/* Packages */
import { createHead } from '@displaycoffee/alexandria/layout/head';

/* Scripts */
import { site } from '@/_core/data/site';
import themeJson from '@/_core/tokens/theme.json' with { type: 'json' }; // generated by tokens-generate (@displaycoffee/tokens)

/* Metadata, viewport, font preloads and font-face styles, built by @displaycoffee/alexandria from the tokens and site data */
export const head = createHead({ site, themeJson });
