/* Packages */
import { getFonts } from '@displaycoffee/tokens';

/* Scripts */
import themeJson from '@/_core/tokens/theme.json' with { type: 'json' }; // generated by tokens-generate (@displaycoffee/tokens)

export const fonts = getFonts(themeJson);
