/* Do not edit directly, this file was generated by scripts/icons-generate.mjs from icons.json. */
/* Packages */
import type { IconifyIcon } from '@iconify/react';

/* Icons used in this project, keyed by name (lucide) or 'prefix:name' (other sets) */
export const icons = {
	'circle-alert': {
		body: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 8v4m0 4h.01"/></g>',
		width: 24,
		height: 24,
	},
	'circle-check': {
		body: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="m16 9l-5.5 5.5L8 12"/></g>',
		width: 24,
		height: 24,
	},
	'circle-x': {
		body: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="m15 9l-6 6m0-6l6 6"/></g>',
		width: 24,
		height: 24,
	},
	house: {
		body: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></g>',
		width: 24,
		height: 24,
	},
	info: {
		body: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4m0-4h.01"/></g>',
		width: 24,
		height: 24,
	},
} satisfies Record<string, IconifyIcon>;
